### ISSUE TITLE
Synaptic not work on Wayland

### ISSUE THREAD

**Issue by vanillajonathan** [mvo5/synaptic#15]

**Comment by gunterkoenigsmann** [comment]
The problem that causes this is that in order to improve security wayland doesn't support gui applications to run as root. The preferred way to get root access for an application is to make it run unprivilleged and to elevate the rights of a worker task using policykit, whenever needed.

**Comment by gunterkoenigsmann** [comment]
See also:

- https://bugs.launchpad.net/ubuntu/+source/synaptic/+bug/1551951
- https://bugzilla.redhat.com/show_bug.cgi?id=1274451

**Comment by julian-alarcon** [comment]
See also:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818366

**Comment by franko108** [comment]
Same problem on Debian 9 with Gnome  3.22.3, opening from a menu doesn't work, from shell is such an error:

>$ synaptic-pkexec 
> No protocol specified
Unable to init server: Could not connect: Connection refused
(synaptic:6206): Gtk-WARNING **: cannot open display: :0 

Firstly prompted for a password, and then error above.
Same situation with `synaptic` or `synaptic-pkexec` command. Launched as root or a non root, same error.

**Comment by DarkFenX** [comment]
Doesn't work on 1920x1080 on intel OSS drivers. I very much doubt it depends on this though.

**Comment by vanillajonathan** [comment]
References to X11:
https://github.com/mvo5/synaptic/search?l=C%2B%2B&q=X11&type=&utf8=%E2%9C%93

**Comment by gunterkoenigsmann** [comment]
Nah... ...it is simpler: Wayland tries to enhance security by making applications choose if they want root rights *or* access to the graphical display. Synaptic wants the first - and therefore doesn't get the latter. The only way around this is drawing the gui from a non-root process and using policykit to create  a worker process that does the things root rights are needed for.

**Comment by Pjotr123** [comment]
@gunterkoenigsmann : I understand, thanks for your explanation.... Is there any chance of us being able to use Synaptic with Wayland, at some point? For me, it's an absolutely essential tool.

**Comment by mvo5** [comment]
Hey, thanks for the problem report. I'm aware of the issue and I'm sorry that I have not tried to fix it yet.

 Unfortunately fixing this is quite a bit of work as it needs some re-architecturing of the current code. Synaptic has a "non-root" mode already but that is read-only. So to get the current behaviour this non-root mode would need a companion dbus service that runs as root and uses policykit and this would need the ability to locks the apt cache  and to commit changes and send the progress (including the dpkg pty) to the non-root part of synaptic. If someone is keen to help with this effort I'm happy to guide. My own time is unfortunately limited to work on this.

**Comment by Pjotr123** [comment]
@mvo5 : thanks for responding! Unfortunately I have no coding skills, so I hope you (or someone else) will be able to find some time to fix this....

**Comment by yareckon** [comment]
Hmm, sounds like a major effort that isn't gonna happen any time soon without some help.  It's not too late for Google Summer of Code for Debian: https://wiki.debian.org/SummerOfCode2018  @mvo5 would you able to participate in that as a mentor?

**Comment by franko108** [comment]
On my Debian 9 (testing repo) synaptic started to work after some updates.
Synaptic version is 0.8.42, kernel 4.14.0-3-amd64, 
GNOME Shell 3.22.3

**Comment by vanillajonathan** [comment]
@franko108 You mean Synaptic version 0.84.2.
http://metadata.ftp-master.debian.org/changelogs/main/s/synaptic/synaptic_0.84.2_changelog

> Depend on policykit-1 instead of recommending
    gksu|kdebase-bin|policykit-1. data/synaptic.desktop.in and
    debian/synaptic.menu both use debian/synaptic-pkexec, which
    unconditionally runs pkexec. (Closes: #856520)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856520

**Comment by franko108** [comment]
@vanillajonathan 
yes, Synaptic version is  0.8.42.
If you need some more information about my setup/dependencies, let me know.

**Comment by geki-yaba** [comment]
> Unfortunately fixing this is quite a bit of work as it needs some re-architecturing of the current code. Synaptic has a "non-root" mode already but that is read-only. So to get the current behaviour this non-root mode would need a companion dbus service that runs as root and uses policykit and this would need the ability to locks the apt cache and to commit changes and send the progress (including the dpkg pty) to the non-root part of synaptic. If someone is keen to help with this effort I'm happy to guide. My own time is unfortunately limited to work on this.

Well, just a dumb idea, but before you do the dbus service from scratch, I'd recommend packagekit with aptcc backend and libpackagekit gobject library. I wonder, if a dpkg pty is still necessary with that? Though, I just don't know.

**Comment by vanillajonathan** [comment]
> Unfortunately fixing this is quite a bit of work as it needs some re-architecturing of the current code. Synaptic has a "non-root" mode already but that is read-only. So to get the current behaviour this non-root mode would need a companion dbus service that runs as root and uses policykit and this would need the ability to locks the apt cache and to commit changes and send the progress (including the dpkg pty) to the non-root part of synaptic. If someone is keen to help with this effort I'm happy to guide. My own time is unfortunately limited to work on this.

If you could get Synaptic to work in read-only mode on Wayland that would a step in the right direction and partially useful in itself.
Synaptic is useful even in read-only mode.

**Comment by AsciiWolf** [comment]
Debian Buster was released today with Wayland as default, but Synaptic unfortunately still does not work on Wayland.

**Comment by vanillajonathan** [comment]
Here is a temporary workaround:

Create a file named  "sugo" with this content:
```sh
#!/bin/sh

[ -n "$@" ] || exit 0
xhost si:localuser:root
sudo $@
xhost -si:localuser:root
```

Give it permission to execute (`chmod +x sugo`). Now you can run `./sugo synaptic` to start Synaptic.

**Comment by AsciiWolf** [comment]
Thanks. I really hope this issue will get properly fixed in a future release.

**Comment by AsciiWolf** [comment]
@mvo5 Just an idea: Couldn't this be solved by creating a specific polkit policy for Synaptic? I think some applications use this on Wayland to run as root and it works.

**Comment by gunterkoenigsmann** [comment]
The graphical user interface of these applications doesn't run as root (at least the ones that don't use Xwayland in order to defeat all security).  But they can use polkit and dbus to order a backend to do things as root.

Synaptic could use already-existing services by telling dbus to tell packagekit to install or uninstall packages...

**Comment by AsciiWolf** [comment]
I am not sure if using PackageKit is a good idea. As far as i know, PackageKit is [deprecated](https://blogs.gnome.org/hughsie/2019/02/14/packagekit-is-dead-long-live-well-something-else/).

**Comment by AsciiWolf** [comment]
[This](https://gitlab.gnome.org/GNOME/mutter/commit/a8984a81c2e887623d69ec9989ae8a5025f7bd47) could help.

**Comment by dupondje** [comment]
Since Gnome/Mutter 3.34, Wayland can run X11 software with root permissions. No need for specific workarounds anymore.
pkexec synaptic just works fine on Ubuntu 19.10 for example now.

But we need to revert/fix https://github.com/mvo5/synaptic/commit/5f3151b19f4277150d501afae915d8f7abfeb0ab#diff-6e0cf79e03f9bdebf99dc9f3759f0950
As since 3.34 its contra productive now :)

**Comment by AsciiWolf** [comment]
GNOME 3.34 is now in Debian Testing and will be in Ubuntu 12.04. @mvo5 Please, consider reverting 5f3151b.

**Comment by AsciiWolf** [comment]
GNOME 3.34 is now in Debian Testing and will be in Ubuntu 20.04. @mvo5 Please, consider reverting 5f3151b.

**Comment by jbicha** [comment]
@mvo5 Ping! Ubuntu 19.10 will be released in [less than a week](https://wiki.ubuntu.com/EoanErmine/ReleaseSchedule)

**Comment by mvo5** [comment]
@jbicha Do we have all the required bits in 19.10 for synaptic to work under wayland?

**Comment by mvo5** [comment]
@jbicha, @AsciiWolf Thanks for the reminder and sorry for my slow reaction. I reverted the patch and uploaded an updated version to both debian and ubuntu.

**Comment by vanillajonathan** [comment]
I guess this issue could be considered kind of resolved. Which would bring us to the next issue, that Synaptic still relies on X, hence requires XWayland. Also, not sure it works on any other Wayland environment other than GNOME.

**Comment by AsciiWolf** [comment]
I see that this issue was most likely fixed in 0.84.7. Thanks! :-)

**Comment by Isakku** [comment]
I consider Synaptic package manager critical for my usage of debian based distros (Ubuntu, Mint, etc.) If Mint 20 would come with Wayland as some people are asking for, I really hope there will be no problems whatsoever.

**Comment by Vicente-M** [comment]
[https://www.linuxtricks.fr/news/10-logiciels-libres/439-lancer-synaptic-en-root-avec-wayland-sous-debian-gnome/](url)

**Comment by leagris** [comment]
Does not work for ssh -X user@host: sudo synaptic.

**Comment by goyodiaz** [comment]
This issue have been solved for several gnome releases already and should be closed. Non-root GUI + policykit would be nice to have but having synaptic work on wayland no longer depends on it.

**Comment by rwperrott** [comment]
> This issue have been solved for several gnome releases already and should be closed. Non-root GUI + policykit would be nice to have but having synaptic work on wayland no longer depends on it.

It still isn't working, several years later in (2024-07-04-raspios-bookworm-armhf.img.xz) RaspIOS 32-bit bookworm, so it should stay open until _really_ fixed. This is quite disappointing.

**Comment by rwperrott** [comment]
The "waysu" script provided by "S. Chauveau" for [How to run graphical applications as root under wayland](https://unix.stackexchange.com/users/533695/s-chauveau) , using [waypipe](https://gitlab.freedesktop.org/mstoeckl/waypipe)  mentioned in the prior answer, can replace pkexec in the /usr/bin/synaptic-pkexec script file.

_My concern was that I didn't see a root password prompt when run on RaspiOS_, **which maybe a security bug in Wayland!** Probably Wayland will have to close this hole and provide an approved way to request a super user access session, and not just assume that no interactive task will need this; repeated root password prompts gets old really-fast, e.g. when using admin:// file URIs to edit system files!

**Comment by n00bieHome** [comment]
The trick to start Synaptic anyway is actually very simple. Just use Krusader for it. Start Krusader in non root mode, go into root mode in the programm, start a shell and start Synaptic. It will run. :) Tested on Ubuntu 24.04 over ssh.

**Comment by leagris** [comment]
Nine years later in 2026 and this issue is still open. Synaptic is still broken or unreliable on Wayland in places like Ubuntu 25.10 and Raspberry Pi OS because of how pkexec and Wayland handle privileged GUIs. The Krusader trick is clever, sure, but after almost a decade of people coming up with these kinds of workarounds (env forwarding, sudo -E tweaks, xhost hacks, waypipe stuff), it's obvious this isn't getting fixed properly upstream.

Wayland's security choices make sense on paper, but when they leave common admin tools like this dead in the water with no good migration path, it doesn't feel like progress. It feels like users are being told to deal with it or go back to Xorg. We've seen this same pattern pop up in other parts of the desktop Linux world lately: strong architectural decisions that break real workflows without solid alternatives. People get tired of it.

@mvo5, is there any realistic chance of fixing this properly (maybe a better PolicyKit integration or rewriting parts of Synaptic), or should we just accept it's never going to work on Wayland and close the issue as a design incompatibility? At least that way new people stumbling in here know what to expect.

**Comment by n00bieHome** [comment]
I don't know if Synaptic still is a good idea for modern operating systems and you are right, ofcourse. But it really works the way i tested it, without problems.  I think if we want to carry an old program like Synaptic to the modern world it really needs a lot of rewriting. I use it now and then, but also most of the time i use other programs for it. :) Synaptic is great to get an overview for all your packages and rest configs. Not all of us are that good at the command line and if i talk for myself, i do not even want to be.  I like graphical things, call me a click nerd. :) Maybe someone on this planet thinks the same way as i do and rewrites the program so that it can handle all that the modern world is asking from a package manager. :)

**Comment by bcutter** [comment]
No working solution. Synaptic under Debian 13 on Wayland. Only temporary solution (from https://www.reddit.com/r/debian/comments/o97s0o/comment/h3a2v21/) is
```
xhost +si:localuser:root
sudo -H synaptic
xhost -si:localuser:root
```

That's way too hacky (/risky) and therefore (for me) probably the death of Synaptic.
